[package]
name = "adl-sys"
version = "0.1.0"
authors = ["shm11C3"]
edition = "2021"
license = "MIT"
keywords = ["AMD", "adl", "radeon"]

[build-dependencies]
bindgen = "0.71.1"

[dependencies]
libloading = "0.8.6"
once_cell = "1.18"
